# config.yml
skill_attributes:
  life_force: 1.0
  strength: 0.5
  tenacity:
    knockback_resistance: 0.003
    toughness: 0.25
  haste:
    attack_speed: 0.02
    movement_speed: 0.001
  precision:
    critical_chance: 0.75
  ferocity:
    critical_damage: 1.5

# Setting for enabling/disabling the xp gain from blocks
gain_xp_from_blocks: true

# Solo Leveling Feature
enable_solo_leveling: true
